CREATE PROCEDURE TrafficStatisticApi.SellableInventoryTrafficStatisticsDelete
@SellableInventoryTrafficStatisticHashKey CHAR (32)
AS
DELETE [TrafficStatistic].[SellableInventoryTrafficStatistics]
WHERE  SellableInventoryTrafficStatisticHashKey = @SellableInventoryTrafficStatisticHashKey;