CREATE TABLE [InventoryGuideAudit].[SellableInventory] (
    [SellableInventoryHashKey]      CHAR (32)     NOT NULL UNIQUE NONCLUSTERED ([SellableInventoryHashKey] ASC),
    [SellableInventorySqn]          INT           IDENTITY (1000, 1) NOT NULL,
    [StationHashKey]                CHAR (32)     NOT NULL,
    [StationGroupHashKey]           CHAR (32)     NOT NULL,
    [RateCardHashKey]               CHAR (32)     NOT NULL,
    [RateCardDaypartHashKey]        CHAR (32)     NOT NULL,
    [RateCardTypeHashKey]           CHAR (32)     NOT NULL,
    [SellingTitleHashKey]           CHAR (32)     NOT NULL,
    [SellingTitleDaysOfWeekHashKey] CHAR (32)     NOT NULL,
    [SellingTitleTimeRangeHashKey]  CHAR (32)     NOT NULL,
    [RatePeriodHashKey]             CHAR (32)     NOT NULL,
    [CreatedDateUtc]                DATETIME2 (7) NOT NULL,
    [ModifiedDateUtc]               DATETIME2 (7) NULL,
    CONSTRAINT [PK_InventoryGuideAudit_SellableInventory_SellableInventoryHashKey] PRIMARY KEY CLUSTERED ([SellableInventoryHashKey] ASC),
    FOREIGN KEY ([RateCardDaypartHashKey]) REFERENCES [InventoryMart].[RateCardDaypart] ([RateCardDaypartHashKey]),
    FOREIGN KEY ([RateCardHashKey]) REFERENCES [InventoryMart].[RateCard] ([RateCardHashKey]),
    FOREIGN KEY ([RateCardTypeHashKey]) REFERENCES [InventoryMart].[RateCardType] ([RateCardTypeHashKey]),
    FOREIGN KEY ([RatePeriodHashKey]) REFERENCES [InventoryMart].[RatePeriod] ([RatePeriodHashKey]),
    FOREIGN KEY ([SellingTitleDaysOfWeekHashKey]) REFERENCES [InventoryMart].[SellingTitleDaysOfWeek] ([SellingTitleDaysOfWeekHashKey]),
    FOREIGN KEY ([SellingTitleHashKey]) REFERENCES [InventoryMart].[SellingTitle] ([SellingTitleHashKey]),
    FOREIGN KEY ([SellingTitleTimeRangeHashKey]) REFERENCES [InventoryMart].[SellingTitleTimeRange] ([SellingTitleTimeRangeHashKey]),
    FOREIGN KEY ([StationGroupHashKey]) REFERENCES [InventoryMart].[StationGroup] ([StationGroupHashKey]),
    FOREIGN KEY ([StationHashKey]) REFERENCES [InventoryMart].[Station] ([StationHashKey])
);

