// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RatingCuration.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Videa.RatingCuration.Service.Proto.Types {
  public static partial class RatingCurationService
  {
    static readonly string __ServiceName = "RatingCurationService";

    static readonly grpc::Marshaller<global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest> __Marshaller_CurateSellerRatingsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse> __Marshaller_CurateSellerRatingsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest, global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse> __Method_CurateSellerRatings = new grpc::Method<global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest, global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CurateSellerRatings",
        __Marshaller_CurateSellerRatingsRequest,
        __Marshaller_CurateSellerRatingsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Videa.RatingCuration.Service.Proto.Types.RatingCurationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RatingCurationService</summary>
    public abstract partial class RatingCurationServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse> CurateSellerRatings(global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RatingCurationService</summary>
    public partial class RatingCurationServiceClient : grpc::ClientBase<RatingCurationServiceClient>
    {
      /// <summary>Creates a new client for RatingCurationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RatingCurationServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RatingCurationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RatingCurationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RatingCurationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RatingCurationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse CurateSellerRatings(global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CurateSellerRatings(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse CurateSellerRatings(global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CurateSellerRatings, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse> CurateSellerRatingsAsync(global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CurateSellerRatingsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsResponse> CurateSellerRatingsAsync(global::Videa.RatingCuration.Service.Proto.Types.CurateSellerRatingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CurateSellerRatings, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RatingCurationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RatingCurationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RatingCurationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CurateSellerRatings, serviceImpl.CurateSellerRatings).Build();
    }

  }
}
#endregion
