// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RateCardConfirmation.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Videa.RateCardConfirmation.Service.Proto.Types {
  public static partial class RateCardConfirmationService
  {
    static readonly string __ServiceName = "RateCardConfirmationService";

    static readonly grpc::Marshaller<global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest> __Marshaller_ConfirmRateCardRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse> __Marshaller_ConfirmRateCardResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest, global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse> __Method_ConfirmRateCard = new grpc::Method<global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest, global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ConfirmRateCard",
        __Marshaller_ConfirmRateCardRequest,
        __Marshaller_ConfirmRateCardResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Videa.RateCardConfirmation.Service.Proto.Types.RateCardConfirmationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RateCardConfirmationService</summary>
    public abstract partial class RateCardConfirmationServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse> ConfirmRateCard(global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RateCardConfirmationService</summary>
    public partial class RateCardConfirmationServiceClient : grpc::ClientBase<RateCardConfirmationServiceClient>
    {
      /// <summary>Creates a new client for RateCardConfirmationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RateCardConfirmationServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RateCardConfirmationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RateCardConfirmationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RateCardConfirmationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RateCardConfirmationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse ConfirmRateCard(global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ConfirmRateCard(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse ConfirmRateCard(global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ConfirmRateCard, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse> ConfirmRateCardAsync(global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ConfirmRateCardAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardResponse> ConfirmRateCardAsync(global::Videa.RateCardConfirmation.Service.Proto.Types.ConfirmRateCardRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ConfirmRateCard, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RateCardConfirmationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RateCardConfirmationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RateCardConfirmationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ConfirmRateCard, serviceImpl.ConfirmRateCard).Build();
    }

  }
}
#endregion
