// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryGuideService.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Videa.InventoryGuideNS.Service.Proto.Types {
  public static partial class InventoryGuideService
  {
    static readonly string __ServiceName = "InventoryGuideService";

    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest> __Marshaller_SellingTitleDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse> __Marshaller_SellingTitleDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest> __Marshaller_StationDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse> __Marshaller_StationDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest> __Marshaller_StationGroupDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse> __Marshaller_StationGroupDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest> __Marshaller_RateCardDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse> __Marshaller_RateCardDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest> __Marshaller_RateCardDaypartDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse> __Marshaller_RateCardDaypartDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest> __Marshaller_RateCardTypeDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse> __Marshaller_RateCardTypeDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest> __Marshaller_SellingTitleTimeRangeDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse> __Marshaller_SellingTitleTimeRangeDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest> __Marshaller_SellingTitleDaysOfWeekDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse> __Marshaller_SellingTitleDaysOfWeekDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest> __Marshaller_RatePeriodDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse> __Marshaller_RatePeriodDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest> __Marshaller_SellableInventoryDeleteRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse> __Marshaller_SellableInventoryDeleteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest> __Marshaller_SellingTitleAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse> __Marshaller_SellingTitleAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest> __Marshaller_StationAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse> __Marshaller_StationAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest> __Marshaller_StationGroupAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse> __Marshaller_StationGroupAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest> __Marshaller_RateCardAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse> __Marshaller_RateCardAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest> __Marshaller_RateCardDaypartAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse> __Marshaller_RateCardDaypartAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest> __Marshaller_RateCardTypeAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse> __Marshaller_RateCardTypeAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest> __Marshaller_SellingTitleTimeRangeAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse> __Marshaller_SellingTitleTimeRangeAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest> __Marshaller_SellingTitleDaysOfWeekAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse> __Marshaller_SellingTitleDaysOfWeekAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest> __Marshaller_RatePeriodAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse> __Marshaller_RatePeriodAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest> __Marshaller_SellableInventoryAddUpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse> __Marshaller_SellableInventoryAddUpdateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest> __Marshaller_GetRateCardsByStationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse> __Marshaller_GetRateCardsByStationResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest> __Marshaller_GetRateCardsByDateRangeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse> __Marshaller_GetRateCardsByDateRangeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest> __Marshaller_GetUnconfirmedInventoryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse> __Marshaller_GetUnconfirmedInventoryResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest> __Marshaller_BulkStoreRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse> __Marshaller_BulkStoreResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse> __Method_SellingTitleDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SellingTitleDelete",
        __Marshaller_SellingTitleDeleteRequest,
        __Marshaller_SellingTitleDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse> __Method_StationDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StationDelete",
        __Marshaller_StationDeleteRequest,
        __Marshaller_StationDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse> __Method_StationGroupDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StationGroupDelete",
        __Marshaller_StationGroupDeleteRequest,
        __Marshaller_StationGroupDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse> __Method_RateCardDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RateCardDelete",
        __Marshaller_RateCardDeleteRequest,
        __Marshaller_RateCardDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse> __Method_RateCardDaypartDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RateCardDaypartDelete",
        __Marshaller_RateCardDaypartDeleteRequest,
        __Marshaller_RateCardDaypartDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse> __Method_RateCardTypeDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RateCardTypeDelete",
        __Marshaller_RateCardTypeDeleteRequest,
        __Marshaller_RateCardTypeDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse> __Method_SellingTitleTimeRangeDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SellingTitleTimeRangeDelete",
        __Marshaller_SellingTitleTimeRangeDeleteRequest,
        __Marshaller_SellingTitleTimeRangeDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse> __Method_SellingTitleDaysOfWeekDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SellingTitleDaysOfWeekDelete",
        __Marshaller_SellingTitleDaysOfWeekDeleteRequest,
        __Marshaller_SellingTitleDaysOfWeekDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse> __Method_RatePeriodDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RatePeriodDelete",
        __Marshaller_RatePeriodDeleteRequest,
        __Marshaller_RatePeriodDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse> __Method_SellableInventoryDelete = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SellableInventoryDelete",
        __Marshaller_SellableInventoryDeleteRequest,
        __Marshaller_SellableInventoryDeleteResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse> __Method_SellingTitleAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SellingTitleAddUpdate",
        __Marshaller_SellingTitleAddUpdateRequest,
        __Marshaller_SellingTitleAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse> __Method_StationAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StationAddUpdate",
        __Marshaller_StationAddUpdateRequest,
        __Marshaller_StationAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse> __Method_StationGroupAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StationGroupAddUpdate",
        __Marshaller_StationGroupAddUpdateRequest,
        __Marshaller_StationGroupAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse> __Method_RateCardAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RateCardAddUpdate",
        __Marshaller_RateCardAddUpdateRequest,
        __Marshaller_RateCardAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse> __Method_RateCardDaypartAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RateCardDaypartAddUpdate",
        __Marshaller_RateCardDaypartAddUpdateRequest,
        __Marshaller_RateCardDaypartAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse> __Method_RateCardTypeAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RateCardTypeAddUpdate",
        __Marshaller_RateCardTypeAddUpdateRequest,
        __Marshaller_RateCardTypeAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse> __Method_SellingTitleTimeRangeAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SellingTitleTimeRangeAddUpdate",
        __Marshaller_SellingTitleTimeRangeAddUpdateRequest,
        __Marshaller_SellingTitleTimeRangeAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse> __Method_SellingTitleDaysOfWeekAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SellingTitleDaysOfWeekAddUpdate",
        __Marshaller_SellingTitleDaysOfWeekAddUpdateRequest,
        __Marshaller_SellingTitleDaysOfWeekAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse> __Method_RatePeriodAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RatePeriodAddUpdate",
        __Marshaller_RatePeriodAddUpdateRequest,
        __Marshaller_RatePeriodAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse> __Method_SellableInventoryAddUpdate = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SellableInventoryAddUpdate",
        __Marshaller_SellableInventoryAddUpdateRequest,
        __Marshaller_SellableInventoryAddUpdateResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse> __Method_GetRateCardsByStation = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRateCardsByStation",
        __Marshaller_GetRateCardsByStationRequest,
        __Marshaller_GetRateCardsByStationResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse> __Method_GetRateCardsByDateRange = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRateCardsByDateRange",
        __Marshaller_GetRateCardsByDateRangeRequest,
        __Marshaller_GetRateCardsByDateRangeResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse> __Method_GetUnconfirmedInventory = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUnconfirmedInventory",
        __Marshaller_GetUnconfirmedInventoryRequest,
        __Marshaller_GetUnconfirmedInventoryResponse);

    static readonly grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse> __Method_BulkStore = new grpc::Method<global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest, global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BulkStore",
        __Marshaller_BulkStoreRequest,
        __Marshaller_BulkStoreResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Videa.InventoryGuideNS.Service.Proto.Types.InventoryGuideServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of InventoryGuideService</summary>
    public abstract partial class InventoryGuideServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse> SellingTitleDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse> StationDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse> StationGroupDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse> RateCardDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse> RateCardDaypartDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse> RateCardTypeDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse> SellingTitleTimeRangeDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse> SellingTitleDaysOfWeekDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse> RatePeriodDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse> SellableInventoryDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse> SellingTitleAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse> StationAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse> StationGroupAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse> RateCardAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse> RateCardDaypartAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse> RateCardTypeAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse> SellingTitleTimeRangeAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse> SellingTitleDaysOfWeekAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse> RatePeriodAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse> SellableInventoryAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse> GetRateCardsByStation(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse> GetRateCardsByDateRange(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse> GetUnconfirmedInventory(global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse> BulkStore(global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InventoryGuideService</summary>
    public partial class InventoryGuideServiceClient : grpc::ClientBase<InventoryGuideServiceClient>
    {
      /// <summary>Creates a new client for InventoryGuideService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public InventoryGuideServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InventoryGuideService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public InventoryGuideServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected InventoryGuideServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected InventoryGuideServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse SellingTitleDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse SellingTitleDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SellingTitleDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse> SellingTitleDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteResponse> SellingTitleDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SellingTitleDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse StationDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StationDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse StationDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StationDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse> StationDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StationDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteResponse> StationDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.StationDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StationDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse StationGroupDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StationGroupDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse StationGroupDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StationGroupDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse> StationGroupDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StationGroupDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteResponse> StationGroupDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StationGroupDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse RateCardDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse RateCardDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RateCardDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse> RateCardDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteResponse> RateCardDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RateCardDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse RateCardDaypartDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardDaypartDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse RateCardDaypartDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RateCardDaypartDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse> RateCardDaypartDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardDaypartDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteResponse> RateCardDaypartDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RateCardDaypartDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse RateCardTypeDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardTypeDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse RateCardTypeDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RateCardTypeDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse> RateCardTypeDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardTypeDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteResponse> RateCardTypeDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RateCardTypeDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse SellingTitleTimeRangeDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleTimeRangeDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse SellingTitleTimeRangeDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SellingTitleTimeRangeDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse> SellingTitleTimeRangeDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleTimeRangeDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteResponse> SellingTitleTimeRangeDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SellingTitleTimeRangeDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse SellingTitleDaysOfWeekDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleDaysOfWeekDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse SellingTitleDaysOfWeekDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SellingTitleDaysOfWeekDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse> SellingTitleDaysOfWeekDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleDaysOfWeekDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteResponse> SellingTitleDaysOfWeekDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SellingTitleDaysOfWeekDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse RatePeriodDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RatePeriodDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse RatePeriodDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RatePeriodDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse> RatePeriodDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RatePeriodDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteResponse> RatePeriodDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RatePeriodDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse SellableInventoryDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellableInventoryDelete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse SellableInventoryDelete(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SellableInventoryDelete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse> SellableInventoryDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellableInventoryDeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteResponse> SellableInventoryDeleteAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SellableInventoryDelete, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse SellingTitleAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse SellingTitleAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SellingTitleAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse> SellingTitleAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateResponse> SellingTitleAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SellingTitleAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse StationAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StationAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse StationAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StationAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse> StationAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StationAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateResponse> StationAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.StationAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StationAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse StationGroupAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StationGroupAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse StationGroupAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StationGroupAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse> StationGroupAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StationGroupAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateResponse> StationGroupAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.StationGroupAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StationGroupAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse RateCardAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse RateCardAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RateCardAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse> RateCardAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateResponse> RateCardAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RateCardAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse RateCardDaypartAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardDaypartAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse RateCardDaypartAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RateCardDaypartAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse> RateCardDaypartAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardDaypartAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateResponse> RateCardDaypartAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardDaypartAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RateCardDaypartAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse RateCardTypeAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardTypeAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse RateCardTypeAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RateCardTypeAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse> RateCardTypeAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RateCardTypeAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateResponse> RateCardTypeAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RateCardTypeAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RateCardTypeAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse SellingTitleTimeRangeAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleTimeRangeAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse SellingTitleTimeRangeAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SellingTitleTimeRangeAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse> SellingTitleTimeRangeAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleTimeRangeAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateResponse> SellingTitleTimeRangeAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleTimeRangeAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SellingTitleTimeRangeAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse SellingTitleDaysOfWeekAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleDaysOfWeekAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse SellingTitleDaysOfWeekAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SellingTitleDaysOfWeekAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse> SellingTitleDaysOfWeekAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellingTitleDaysOfWeekAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateResponse> SellingTitleDaysOfWeekAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellingTitleDaysOfWeekAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SellingTitleDaysOfWeekAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse RatePeriodAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RatePeriodAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse RatePeriodAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RatePeriodAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse> RatePeriodAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RatePeriodAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateResponse> RatePeriodAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.RatePeriodAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RatePeriodAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse SellableInventoryAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellableInventoryAddUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse SellableInventoryAddUpdate(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SellableInventoryAddUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse> SellableInventoryAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SellableInventoryAddUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateResponse> SellableInventoryAddUpdateAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.SellableInventoryAddUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SellableInventoryAddUpdate, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse GetRateCardsByStation(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRateCardsByStation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse GetRateCardsByStation(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRateCardsByStation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse> GetRateCardsByStationAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRateCardsByStationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationResponse> GetRateCardsByStationAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByStationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRateCardsByStation, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse GetRateCardsByDateRange(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRateCardsByDateRange(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse GetRateCardsByDateRange(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRateCardsByDateRange, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse> GetRateCardsByDateRangeAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRateCardsByDateRangeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeResponse> GetRateCardsByDateRangeAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.GetRateCardsByDateRangeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRateCardsByDateRange, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse GetUnconfirmedInventory(global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUnconfirmedInventory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse GetUnconfirmedInventory(global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUnconfirmedInventory, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse> GetUnconfirmedInventoryAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUnconfirmedInventoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryResponse> GetUnconfirmedInventoryAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.GetUnconfirmedInventoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUnconfirmedInventory, null, options, request);
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse BulkStore(global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return BulkStore(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse BulkStore(global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BulkStore, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse> BulkStoreAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return BulkStoreAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreResponse> BulkStoreAsync(global::Videa.InventoryGuideNS.Service.Proto.Types.BulkStoreRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BulkStore, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override InventoryGuideServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InventoryGuideServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(InventoryGuideServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SellingTitleDelete, serviceImpl.SellingTitleDelete)
          .AddMethod(__Method_StationDelete, serviceImpl.StationDelete)
          .AddMethod(__Method_StationGroupDelete, serviceImpl.StationGroupDelete)
          .AddMethod(__Method_RateCardDelete, serviceImpl.RateCardDelete)
          .AddMethod(__Method_RateCardDaypartDelete, serviceImpl.RateCardDaypartDelete)
          .AddMethod(__Method_RateCardTypeDelete, serviceImpl.RateCardTypeDelete)
          .AddMethod(__Method_SellingTitleTimeRangeDelete, serviceImpl.SellingTitleTimeRangeDelete)
          .AddMethod(__Method_SellingTitleDaysOfWeekDelete, serviceImpl.SellingTitleDaysOfWeekDelete)
          .AddMethod(__Method_RatePeriodDelete, serviceImpl.RatePeriodDelete)
          .AddMethod(__Method_SellableInventoryDelete, serviceImpl.SellableInventoryDelete)
          .AddMethod(__Method_SellingTitleAddUpdate, serviceImpl.SellingTitleAddUpdate)
          .AddMethod(__Method_StationAddUpdate, serviceImpl.StationAddUpdate)
          .AddMethod(__Method_StationGroupAddUpdate, serviceImpl.StationGroupAddUpdate)
          .AddMethod(__Method_RateCardAddUpdate, serviceImpl.RateCardAddUpdate)
          .AddMethod(__Method_RateCardDaypartAddUpdate, serviceImpl.RateCardDaypartAddUpdate)
          .AddMethod(__Method_RateCardTypeAddUpdate, serviceImpl.RateCardTypeAddUpdate)
          .AddMethod(__Method_SellingTitleTimeRangeAddUpdate, serviceImpl.SellingTitleTimeRangeAddUpdate)
          .AddMethod(__Method_SellingTitleDaysOfWeekAddUpdate, serviceImpl.SellingTitleDaysOfWeekAddUpdate)
          .AddMethod(__Method_RatePeriodAddUpdate, serviceImpl.RatePeriodAddUpdate)
          .AddMethod(__Method_SellableInventoryAddUpdate, serviceImpl.SellableInventoryAddUpdate)
          .AddMethod(__Method_GetRateCardsByStation, serviceImpl.GetRateCardsByStation)
          .AddMethod(__Method_GetRateCardsByDateRange, serviceImpl.GetRateCardsByDateRange)
          .AddMethod(__Method_GetUnconfirmedInventory, serviceImpl.GetUnconfirmedInventory)
          .AddMethod(__Method_BulkStore, serviceImpl.BulkStore).Build();
    }

  }
}
#endregion
